apiVersion: v1
kind: Service
metadata:
  name: mlops-app-service
spec:
  selector:
    app: mlops-app
  ports:
    - protocol: "TCP"
      port: 5000
      targetPort: 5000
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlops-app
spec:
  selector:
    matchLabels:
      app: mlops-app
  replicas: 1
  template:
    metadata:
      labels:
        app: mlops-app
    spec:
      containers:
        - name: mlops-app
          image: ldomotor/mlops-app:49a518b
          ports:
            - containerPort: 8080
